lbms/urls.py
from django.contrib import admin
from django.urls import path, include, re_path

urlpatterns = [
    re_path(r'^', include('lbms_app.urls')),
    path('', admin.site.urls),
]

lbms_app/urls.py
from django.urls import re_path

from lbms_app.views import get_monthly_data, get_yearly_data, MonthlyStatsView, YearlyStatsView

app_name = 'lbms_app'

urlpatterns = [
    re_path(r'^data/m$', get_monthly_data, name='get_monthly_data'),
    re_path(r'^data/y$', get_yearly_data, name='get_yearly_data'),
    re_path(r'^stats/m$', MonthlyStatsView.as_view(), name='stats'),
    re_path(r'^stats/m$', MonthlyStatsView.as_view(), name='m_stats'),
    re_path(r'^stats/y$', YearlyStatsView.as_view(), name='y_stats'),
]

lbms_app/models.py
from datetime import date

from django.conf import settings
from django.contrib.auth.models import AbstractUser
from django.core.exceptions import ValidationError
from django.core.validators import MinValueValidator
from django.db import models
from django.utils.formats import date_format
from django.utils.translation import gettext_lazy as _


class NamedMixin(models.Model):
    class Meta:
        abstract = True

    name = models.CharField(max_length=100, verbose_name=_('name'))


class Group(NamedMixin):
    def __str__(self):
        return self.name


class GroupMixin(models.Model):
    class Meta:
        abstract = True

    lbms_group = models.ForeignKey(Group, on_delete=models.CASCADE)


class User(AbstractUser, GroupMixin):
    lbms_group = models.ForeignKey(Group, on_delete=models.PROTECT)


class Category(NamedMixin, GroupMixin):
    class Meta:
        verbose_name = _('category')
        verbose_name_plural = _('categories')

    parent = models.ForeignKey(
        'self',
        null=True,
        blank=True,
        on_delete=models.RESTRICT,
        related_name='children',
        verbose_name=_('parent')
    )
    add_date = models.DateField(auto_now_add=True)

    def __str__(self):
        return self.name

    def clean(self):
        if self.parent:
            if self in self.parent.ancestors():
                raise ValidationError(_('Parent and child nodes cannot be the same, or have a cyclic relationship.'))

            if self.parent.lbms_group != self.lbms_group:
                raise ValidationError('Parent and child must have the same group')

    def ancestors(self):
        if self.parent:
            yield from self.parent.ancestors()

        yield self


class Source(NamedMixin, GroupMixin):
    class Meta:
        verbose_name = _('source')
        verbose_name_plural = _('sources')

    def __str__(self):
        return self.name


class Expense(GroupMixin):
    class Meta:
        verbose_name = _('expense')
        verbose_name_plural = _('expenses')

    amount = models.DecimalField(max_digits=8, decimal_places=2, verbose_name=_('amount') + ' (€)',
                                 validators=[MinValueValidator(0)])
    category = models.ForeignKey(Category, on_delete=models.RESTRICT, verbose_name=_('category'))
    source = models.ForeignKey(Source, on_delete=models.RESTRICT, verbose_name=_('source'))
    date = models.DateField(default=date.today, verbose_name=_('date'))

    def clean(self):
        if not all((
                hasattr(self, 'lbms_group', ),
                hasattr(self, 'source'),
                hasattr(self, 'category')
        )):
            raise ValidationError(_('Required fields missing.'))

        if not (self.lbms_group == self.source.lbms_group == self.category.lbms_group):
            raise ValidationError('Expense, source and category must have the same group')

    def __str__(self):
        return _('€ {amount} on {date} for {category} from {source}').format(
            amount=self.amount,
            date=date_format(self.date, settings.DATE_FORMAT),
            category=self.category,
            source=self.source
        )

lbms_app/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.db.models import Q
from django.utils.datetime_safe import date
from django.utils.translation import gettext as _

from lbms_app.models import Expense, Category, Source

User = get_user_model()


class NoGroupForm(forms.ModelForm):
    class Meta:
        exclude = 'lbms_group',


class CategoryForm(NoGroupForm):
    class Meta(NoGroupForm.Meta):
        model = Category

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        queryset = CategoryForm.Meta.model.objects \
            .filter(lbms_group=self.lbms_group) \
            .order_by('name')

        if self.instance:
            queryset = queryset.exclude(id=self.instance.id)

        self.fields['parent'] = forms.ModelChoiceField(queryset, required=False, label=_('parent').title())


class SourceForm(NoGroupForm):
    class Meta(NoGroupForm.Meta):
        model = Source


class ExpenseForm(NoGroupForm):
    class Meta(NoGroupForm.Meta):
        model = Expense

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)

        first_of_month = date.today().replace(day=1)

        category_queryset = Category.objects \
            .filter(lbms_group=self.lbms_group) \
            .filter(add_date__lt=first_of_month) \
            .filter(Q(children=None) | Q(children__add_date__gt=first_of_month)) \
            .order_by('name')

        source_queryset = Source.objects \
            .filter(lbms_group=self.lbms_group) \
            .order_by('name')

        self.fields['category'] = forms.ModelChoiceField(category_queryset, label=_('category').title())
        self.fields['source'] = forms.ModelChoiceField(source_queryset, label=_('source').title())

lbms_app/views.py
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse, HttpResponseBadRequest
from django.views.generic import TemplateView

from lbms_app.models import Expense, Category, Source
from lbms_app.utils.buckets import make_buckets


def expense_sum(expenses):
    return sum(expense.amount for expense in expenses)


def month_expenses(group, year, month):
    return Expense.objects.filter(lbms_group=group, date__year=year, date__month=month)


def total_source_category(expenses, group):
    categories = set(expense.category for expense in expenses)
    buckets = make_buckets(categories, Category.ancestors)

    return {
        'total': expense_sum(expenses),

        'by_category': {
            category.name: expense_sum(expenses.filter(category__in=buckets[category]))
            for category in buckets
        },

        'by_source': {
            source.name: expense_sum(expenses.filter(source=source))
            for source in Source.objects.filter(lbms_group=group)
        },
    }


@login_required
def get_monthly_data(request):
    try:
        assert request.method == 'GET'

        year, month = map(int, (request.GET.get('year'), request.GET.get('month')))

        assert 2015 < year
        assert month in range(1, 12 + 1)

    except (AssertionError, TypeError, ValueError):
        return HttpResponseBadRequest()

    # noinspection PyUnresolvedReferences
    group = request.user.lbms_group
    month_expenses_ = month_expenses(group, year, month)

    return JsonResponse({
        **total_source_category(month_expenses_, group),
    })


@login_required
def get_yearly_data(request):
    try:
        assert request.method == 'GET'

        year = int(request.GET.get('year'))

        assert 2015 < year

    except (AssertionError, TypeError, ValueError):
        return HttpResponseBadRequest()

    # noinspection PyUnresolvedReferences
    group = request.user.lbms_group
    year_expenses = Expense.objects.filter(lbms_group=group, date__year=year)

    return JsonResponse({
        **total_source_category(year_expenses, group),

        'by_month': {
            month: expense_sum(month_expenses(group, year, month))
            for month in range(1, 12 + 1)
        }
    })


class MonthlyStatsView(LoginRequiredMixin, TemplateView):
    template_name = "lbms_app/m_stats.html"


class YearlyStatsView(LoginRequiredMixin, TemplateView):
    template_name = "lbms_app/y_stats.html"

lbms_app/templates/lbms_app/base.html
<!DOCTYPE html>
<html lang="it">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- style -->
        <link type="text/css" rel="stylesheet" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <!-- script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

        {% include "lbms_app/pwa.html" %}

        {% block scripts %} {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        LBMS | Statistiche
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'admin:index' %}">Spese</a></li>
                        {% block navbar_links %} {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="content">
            <div class="container">
                {% block content %} {% endblock %}
            </div>
        </div>
    </body>
</html>

lbms_app/templates/lbms_app/m_stats.html
{% extends "lbms_app/stats.html" %}
{% block navbar_links %}
    <li><a href="{% url 'lbms_app:y_stats' %}">Statistiche Annuali</a></li>
{% endblock %}
{% block update %}

$('#month-name').html($('#month-select option:selected').text())

let url = "{% url 'lbms_app:get_monthly_data' %}"
let params = {
    year: $('#year-input').val(),
    month: $('#month-select').val()
}

{% endblock %}
{% block document_ready %}

month_select = $('#month-select');

$(months).each(function (index, month) {
    month_select.append("<option value=\"" + (index + 1) + "\">" + month + "</option>");
});

$('#month-select option').each(function(){
    let month = new Date().getMonth() - 1;
    let dec = month == 0;
    if (dec) {
        month = 12;
    }

    set_year(dec);

    var $this = $(this); // cache this jQuery object to avoid overhead

    if ($this.val() == month) {
        $this.prop('selected', true);
        return false; // break the loop
    }
});

{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-6">
            <label for="year-input">Anno: </label>
            <input class="form-control" type="number" id="year-input" name="year" min="2015">
        </div>
        <div class="col-sm-6">
            <label for="month-select">Mese: </label>
            <select class="form-control" id="month-select" name="month" required>
            </select>
        </div>
    </div>

    <div class="row">
        <h1 id="month-name"></h1>
        <h3 id="total"></h3>
        <div class="col-sm-6">
            <h3>Categorie:</h3>
            <canvas id="categories_canvas" style="width:100%; height:40vh;"></canvas>
            <br>
            <table><tbody id="categories_data"></tbody></table>
            <br>
        </div>
        <div class="col-sm-6">
            <h3>Provenienze:</h3>
            <canvas id="sources_canvas" style="width:100%; height:40vh;"></canvas>
            <br>
            <table><tbody id="sources_data"></tbody></table>
            <br>
        </div>
    </div>
{% endblock %}

lbms_app/templates/lbms_app/pwa.html
{% load static %}

<meta name="theme-color" content="#417690">
<meta name="mobile-web-app-capable" content="yes">
<meta name="description" content="LBMS">
<link rel="manifest" href="{% static 'manifest.json' %}">
<link rel="shortcut icon" href="{% static 'icons/favicon.png' %}">
<script src="{% static 'js/companion.js' %}" data-service-worker="{% static 'js/sw.js' %}"></script>

lbms_app/templates/lbms_app/stats.html
{% extends "lbms_app/base.html" %}
{% load static %}
{% block title %} LBMS | Statistiche {% endblock %}
{% block pagetitle %} LBMS | Statistiche {% endblock %}
{% block scripts %}
    <script>
        let months = ['Gennaio', 'Febbraio', 'Marzo', 'Aprile', 'Maggio', 'Giugno', 'Luglio', 'Agosto', 'Settembre', 'Ottobre', 'Novembre', 'Dicembre'];

        function draw_pie(data, canvas_id) {
            return new Chart(document.getElementById(canvas_id).getContext('2d'), {
                    type: 'pie',
                    data: {
                        datasets: [{
                            data: $.map(data, function(value, key) { return value }),
                            backgroundColor: [
                                'rgba(255, 206, 86)',
                                'rgba(75, 192, 192)',
                                'rgba(153, 102, 255)',
                                'rgba(255, 159, 64)',
                                'rgba(255, 99, 132)',
                                'rgba(54, 162, 235)',
                                'rgba(255, 206, 86)',
                                'rgba(75, 192, 192)',
                                'rgba(153, 102, 255)',
                                'rgba(255, 159, 64)',
                                'rgba(255, 99, 132)',
                                'rgba(54, 162, 235)',
                                'rgba(255, 206, 86)',
                                'rgba(75, 192, 192)',
                                'rgba(153, 102, 255)',
                                'rgba(255, 159, 64)',
                                'rgba(255, 99, 132)',
                                'rgba(54, 162, 235)',
                            ],
                        }],
                        labels: Object.keys(data)
                    },
                    options: {}
                });
        }

        function draw_bar(data, canvas_id) {
            return new Chart(document.getElementById(canvas_id).getContext('2d'), {
                type: 'bar',
                data: {
                    labels: months,
                    datasets: [{
                        label: [],
                        data: $.map(data, function(value, key) { return value }),
                        backgroundColor: [
                            'rgba(255, 206, 86)',
                            'rgba(75, 192, 192)',
                            'rgba(153, 102, 255)',
                            'rgba(255, 159, 64)',
                            'rgba(255, 99, 132)',
                            'rgba(54, 162, 235)',
                            'rgba(255, 206, 86)',
                            'rgba(75, 192, 192)',
                            'rgba(153, 102, 255)',
                            'rgba(255, 159, 64)',
                            'rgba(255, 99, 132)',
                            'rgba(255, 99, 132)',
                            'rgba(54, 162, 235)',
                        ],
                        borderWidth: 1
                    }]
                },
                options: {
                    scales: {
                        yAxes: [{
                            ticks: {
                                beginAtZero: true
                            }
                        }]
                    }
                },
            });
        }

        function show_data(data, div_id) {
            let div = $('#' + div_id)[0];

            div.innerHTML = '';

            $.map(data, function (value, key) {div.innerHTML += '<tr><td class="stat_list_elem_td">' + key + '</td><td>€ <b>' + value + '</b></td></tr>'});
        }

        function set_year(previous = false) {
            $('#year-input').val(new Date().getFullYear() - previous);
        }

        function update() {
            {% block update %}{% endblock %}
            $.get(url, params, function (data) {
                let categories = draw_pie(data['by_category'], 'categories_canvas');
                let sources = draw_pie(data['by_source'], 'sources_canvas');

                show_data(data['by_category'], 'categories_data');
                show_data(data['by_source'], 'sources_data');

                $('#total').html('Totale: € <b>' + data['total'] + '</b>')

                {% block response %}{% endblock %}
            });
        }

        $(document).ready(function () {
            {% block document_ready %}
            {% endblock %}

            $('#year-input').change(function () {
                update();
            });

            $('#month-select').change(function () {
                update();
            });

            update();
        });
    </script>
{% endblock %}

lbms_app/templates/lbms_app/y_stats.html
{% extends "lbms_app/stats.html" %}
{% block navbar_links %}
    <li><a href="{% url 'lbms_app:m_stats' %}">Statistiche Mensili</a></li>
{% endblock %}
{% block update %}

let url = "{% url 'lbms_app:get_yearly_data' %}"
let params = {
    year: $('#year-input').val()
}

{% endblock %}
{% block response %}

draw_bar(data['by_month'], 'monthly_canvas');
show_data(Object.assign({}, ...$.map(data['by_month'], function(value, key) { return Object.fromEntries([[months[key - 1], value ]]) })), 'monthly_data');

{% endblock %}
{% block document_ready %}

set_year(true);

{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-sm-12">
            <label for="year-input">Anno: </label>
            <input class="form-control" type="number" id="year-input" name="year" min="2015">
        </div>
    </div>

    <div class="row">
        <h3 id="total"></h3>
        <div class="col-sm-6">
            <h3>Categorie:</h3>
            <canvas id="categories_canvas" style="width:100%; height:40vh;"></canvas>
            <br>
            <table><tbody id="categories_data"></tbody></table>
        </div>
        <div class="col-sm-6">
            <h3>Provenienze:</h3>
            <canvas id="sources_canvas" style="width:100%; height:40vh;"></canvas>
            <br>
            <table><tbody id="sources_data"></tbody></table>
        </div>
        <div class="col-sm-12">
            <h3>Distribuzione Mensile:</h3>
            <canvas id="monthly_canvas" style="width:100%; height:40vh;"></canvas>
            <br>
            <table><tbody id="monthly_data"></tbody></table>
            <br>
        </div>
    </div>
{% endblock %}

templates/lbms_app/base.html
<!DOCTYPE html>
<html lang="it">
    <head>
        {% load static %}
        <meta charset="utf-8">
        <title>{% block title %}{% endblock %}</title>
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!-- style -->
        <link type="text/css" rel="stylesheet" href="{% static 'style.css' %}">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
        <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
        <!-- script -->
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
        <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
        <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.bundle.min.js"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.6.0/Chart.min.js"></script>

        {% block scripts %} {% endblock %}
    </head>

    <body>
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#navbar">
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                        <span class="icon-bar"></span>
                    </button>
                    <div class="navbar-brand">
                        LBMS | Statistiche
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="navbar">
                    <ul class="nav navbar-nav">
                        <li><a href="{% url 'admin:index' %}">Spese</a></li>
                        {% block navbar_links %} {% endblock %}
                    </ul>
                </div>
            </div>
        </nav>
        <div id="content">
            <div class="container">
                {% block content %} {% endblock %}
            </div>
        </div>
    </body>
</html>